[tool.black]
line-length = 99
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
skip-string-normalization = true
preview = true
verbose = true

[tool.pytest.ini_options]
asyncio_mode = 'strict'
